//! Huffman literal decoding: tree description parsing and the 1-stream /
//! 4-stream bitstream decoders.
//!
//! The tree description is either a direct nibble table or an FSE-compressed
//! weight stream (RFC 8878 Section 4.2.1). Decoding uses a flat "X1" table of
//! `1 << tableLog` entries, each holding the symbol and the number of bits
//! that symbol consumes.

const std = @import("std");
const bits = @import("../common/bits.zig");
const errors = @import("../common/errors.zig");
const bitstream_mod = @import("../common/bitstream.zig");
const fse_dtable = @import("../fse/dtable.zig");
const ncount_mod = @import("../fse/ncount.zig");

/// Format limit from RFC 8878 Section 4.2.1.1. The reference encoder caps
/// literals tables at 11, but the format allows 12 and a decoder must accept
/// streams produced by encoders that use the full range.
pub const max_table_log: u8 = 12;
/// A 4-stream literals block needs at least this many regenerated bytes,
/// because each stream must produce at least one symbol.
pub const min_lit_size_4_streams: usize = 6;

const Entry = struct {
    symbol: u8,
    nbBits: u8,
};

pub const HuffDecoder = struct {
    /// Flat decoding table with `1 << max_bits` entries, owned by this value.
    table: []Entry,
    max_bits: u8,
    allocator: std.mem.Allocator,

    pub fn deinit(self: *HuffDecoder) void {
        self.allocator.free(self.table);
        self.table = &.{};
    }
};

/// Builds a flat decoding table from explicit Huffman weights. `weights` must be
/// the complete list including the implied final weight, so that
/// `sum(1 << (w - 1)) == 1 << tableLog`.
pub fn buildDecoder(allocator: std.mem.Allocator, weights: []const u8, tableLog: u8) errors.ZstdError!HuffDecoder {
    if (weights.len == 0) return error.InvalidHuffmanTable;
    if (tableLog == 0 or tableLog > max_table_log) return error.InvalidHuffmanTable;
    for (weights) |w| {
        if (w > tableLog) return error.InvalidHuffmanTable;
    }

    const table_size: usize = @as(usize, 1) << @intCast(tableLog);
    const table = try allocator.alloc(Entry, table_size);
    errdefer allocator.free(table);
    @memset(table, .{ .symbol = 0, .nbBits = 0 });

    var rankVal: [max_table_log + 1]u32 = @splat(0);
    for (weights) |w| {
        if (w == 0) continue; // zero-weight symbols are not part of the code
        rankVal[w] += 1;
    }

    // Start cell of each rank; the table is filled rank by rank from the top
    // bit position down, so lower weights (longer codes) come first.
    var rankStart: [max_table_log + 1]usize = undefined;
    var nextRankStart: usize = 0;
    var w: u8 = 1;
    while (w <= tableLog) : (w += 1) {
        rankStart[w] = nextRankStart;
        nextRankStart += @as(usize, rankVal[w]) << @intCast(w - 1);
    }
    if (nextRankStart != table_size) return error.InvalidHuffmanTable;

    var cursor = rankStart;
    for (weights, 0..) |weight, sym| {
        if (weight == 0) continue;
        if (sym > 0xFF) return error.InvalidHuffmanTable;
        const length: usize = @as(usize, 1) << @intCast(weight - 1);
        const entry = Entry{ .symbol = @intCast(sym), .nbBits = tableLog + 1 - weight };
        const start = cursor[weight];
        if (start + length > table_size) return error.InvalidHuffmanTable;
        @memset(table[start .. start + length], entry);
        cursor[weight] = start + length;
    }

    return .{ .table = table, .max_bits = tableLog, .allocator = allocator };
}

/// Parses a Huffman_Tree_Description (RFC 8878 Section 4.2.1.1), writing
/// reconstructed weights into `huffWeight[0..nbSymbols]`, the per-weight
/// histogram into `rankStats`, and returning the description bytes consumed.
/// `allocator` backs only temporary buffers; nothing escapes.
pub fn readStats(
    huffWeight: []u8,
    rankStats: []u32,
    nb_symbols_ptr: *usize,
    table_log_ptr: *u8,
    src: []const u8,
    allocator: std.mem.Allocator,
) errors.ZstdError!usize {
    if (src.len == 0) return error.SrcSizeWrong;
    // Max weight is bounded by the table log, so a 4-bit nibble plus the
    // implied final weight is all the storage we ever need.
    if (huffWeight.len < 256) return error.InvalidHuffmanTable;
    if (rankStats.len < max_table_log + 1) return error.InvalidHuffmanTable;

    var ip: usize = 0;
    const header: u32 = src[0];
    ip += 1;
    var oSize: usize = 0;

    if (header >= 128) {
        // Direct representation: one 4-bit nibble per weight, high nibble
        // first. The weight count is `header - 127`.
        oSize = header - 127;
        const inBytes = (oSize + 1) / 2;
        if (ip + inBytes > src.len) return error.SrcSizeWrong;
        var n: usize = 0;
        while (n < oSize) : (n += 2) {
            huffWeight[n] = src[ip + n / 2] >> 4;
            if (n + 1 < oSize) huffWeight[n + 1] = src[ip + n / 2] & 15;
        }
        ip += inBytes;
    } else {
        if (header == 0) return error.Corruption;
        if (ip + header > src.len) return error.SrcSizeWrong;
        const fse_payload = src[ip .. ip + header];
        ip += header;

        // The weights are FSE-compressed. The FSE table log for this
        // alphabet is bounded at 6 by the format.
        var fse_norm: [256]i16 = undefined;
        var maxSv: usize = 255;
        var fse_log: u8 = 0;
        const ncountRead = try ncount_mod.readNCount(&fse_norm, &maxSv, &fse_log, fse_payload);
        if (fse_log > 6) return error.TableLogTooLarge;
        if (maxSv == 0) return error.Corruption;

        var dt = try fse_dtable.build(allocator, fse_norm[0 .. maxSv + 1], maxSv, fse_log);
        defer dt.deinit();

        const bitstream = fse_payload[ncountRead..];
        var dstream = bitstream_mod.BIT_DStream.init(bitstream) catch return error.Corruption;

        // Two interleaved FSE states, each seeded with `log` bits.
        var s1: u16 = @intCast(dstream.readBits(fse_log));
        var s2: u16 = @intCast(dstream.readBits(fse_log));

        // The weight list is bounded by the 255 explicitly-stored weights; the
        // final weight is implied and appended by the caller.
        const omax: usize = 255;
        var op: usize = 0;

        // Fast path: four symbols per reload while the stream is healthy.
        while (dstream.reload() == .unfinished and op + 4 <= omax) {
            huffWeight[op] = step(&dt, &dstream, &s1);
            huffWeight[op + 1] = step(&dt, &dstream, &s2);
            huffWeight[op + 2] = step(&dt, &dstream, &s1);
            huffWeight[op + 3] = step(&dt, &dstream, &s2);
            op += 4;
        }
        // Tail: alternate until the reload signals the final symbol.
        while (true) {
            if (op + 2 > omax) return error.Corruption;
            huffWeight[op] = step(&dt, &dstream, &s1);
            op += 1;
            if (dstream.reload() == .overflow) {
                huffWeight[op] = step(&dt, &dstream, &s2);
                op += 1;
                break;
            }
            huffWeight[op] = step(&dt, &dstream, &s2);
            op += 1;
            if (dstream.reload() == .overflow) {
                huffWeight[op] = step(&dt, &dstream, &s1);
                op += 1;
                break;
            }
        }
        oSize = op;
        if (oSize == 0) return error.Corruption;
    }

    @memset(rankStats[0 .. max_table_log + 1], 0);
    var weightTotal: u32 = 0;
    for (0..oSize) |n| {
        const w = huffWeight[n];
        if (w > max_table_log) return error.Corruption;
        rankStats[w] += 1;
        if (w > 0) weightTotal += @as(u32, 1) << @as(std.math.Log2Int(u32), @intCast(w - 1));
    }
    if (weightTotal == 0) return error.Corruption;

    // The table log is one above the position of the highest set bit of the
    // total weight; the leftover cells are filled by exactly one more symbol.
    const tableLog: u8 = @intCast(@as(u32, @intCast(31 - @clz(weightTotal))) + 1);
    if (tableLog > max_table_log) return error.Corruption;
    table_log_ptr.* = tableLog;

    const total: u32 = @as(u32, 1) << @as(std.math.Log2Int(u32), @intCast(tableLog));
    const rest = total - weightTotal;
    if (rest == 0 or (rest & (rest - 1)) != 0) return error.Corruption;
    const lastWeight: u8 = @intCast(@as(u32, @intCast(31 - @clz(rest))) + 1);
    if (oSize + 1 > huffWeight.len) return error.Corruption;
    huffWeight[oSize] = lastWeight;
    rankStats[lastWeight] += 1;

    nb_symbols_ptr.* = oSize + 1;

    // A complete code always has an even number of codes at its deepest rank,
    // and never fewer than two. Rejecting anything else here keeps a corrupt
    // description from turning into a subtly wrong table.
    if (rankStats[1] < 2 or (rankStats[1] & 1) != 0) return error.Corruption;

    return ip;
}

/// One FSE decode step: emit the symbol at `state`, then advance the state
/// using `nbBits` freshly read bits.
fn step(dt: *const fse_dtable.DTable, ds: *bitstream_mod.BIT_DStream, state: *u16) u8 {
    const e = dt.entries[state.*];
    const low = ds.readBits(e.nbBits);
    state.* = e.newState +% @as(u16, @truncate(low));
    return @truncate(e.symbol);
}

/// Decodes exactly `dst.len` symbols from a single Huffman bitstream. Reading
/// past the end yields zero-extended bits as the reference decoder does; the
/// caller has already validated the tree. `strict` requires the stream to be
/// exactly exhausted, as the frame decoder needs for untrusted input; the lenient
/// mode exists for encoder output that may carry extra padding.
pub fn decodeSingleStream(dst: []u8, src: []const u8, decoder: *const HuffDecoder) errors.ZstdError!void {
    return decodeSingleStreamInner(dst, src, decoder, true);
}

pub fn decodeSingleStreamLenient(dst: []u8, src: []const u8, decoder: *const HuffDecoder) errors.ZstdError!void {
    return decodeSingleStreamInner(dst, src, decoder, false);
}

fn decodeSingleStreamInner(dst: []u8, src: []const u8, decoder: *const HuffDecoder, strict: bool) errors.ZstdError!void {
    if (dst.len == 0) return;
    var bitStream = try bitstream_mod.BIT_DStream.init(src);
    const tableLog = decoder.max_bits;
    const mask: u64 = (@as(u64, 1) << @as(std.math.Log2Int(u64), @intCast(tableLog))) - 1;

    const pEnd = dst.len;
    var p: usize = 0;

    // Four symbols per reload, then a short tail of at most three.
    if (pEnd > 3) {
        while (bitStream.reload() == .unfinished and p < pEnd - 3) {
            inline for (0..4) |_| {
                const val = bitStream.lookBits(tableLog) & mask;
                const entry = decoder.table[@intCast(val)];
                dst[p] = entry.symbol;
                p += 1;
                bitStream.skipBits(entry.nbBits);
            }
        }
    } else {
        _ = bitStream.reload();
    }

    while (p < pEnd) {
        const val = bitStream.lookBits(tableLog) & mask;
        const entry = decoder.table[@intCast(val)];
        dst[p] = entry.symbol;
        p += 1;
        bitStream.skipBits(entry.nbBits);
    }

    // A well-formed stream is exactly exhausted. Leftover bytes or an
    // over-read both indicate a truncated or corrupt bitstream.
    if (strict) try bitStream.requireCompleted();
}

/// Decodes a 4-stream literals payload: a 6-byte jump table followed by four
/// independent bitstreams that each regenerate one quarter of the output.
pub fn decode4Streams(dst: []u8, src: []const u8, decoder: *const HuffDecoder) errors.ZstdError!void {
    return decode4StreamsInner(dst, src, decoder, true);
}

pub fn decode4StreamsLenient(dst: []u8, src: []const u8, decoder: *const HuffDecoder) errors.ZstdError!void {
    return decode4StreamsInner(dst, src, decoder, false);
}

fn decode4StreamsInner(dst: []u8, src: []const u8, decoder: *const HuffDecoder, strict: bool) errors.ZstdError!void {
    // 6 bytes of jump table plus at least one byte per stream.
    if (src.len < 10) return error.Corruption;
    const o1: usize = bits.readLe16(src[0..2]);
    const o2: usize = bits.readLe16(src[2..4]);
    const o3: usize = bits.readLe16(src[4..6]);
    const s1End: usize = 6 + o1;
    const s2End: usize = s1End + o2;
    const s3End: usize = s2End + o3;
    // The three sizes are 16-bit fields, so the end offsets can exceed a 16-bit
    // type even though the jump table is exact.
    if (s3End > src.len) return error.Corruption;
    const s4Start: usize = s3End;
    if (s4Start >= src.len) return error.Corruption;

    const segment_size = (dst.len + 3) / 4;
    const op2 = segment_size;
    const op3 = op2 + segment_size;
    const op4 = op3 + segment_size;
    if (op4 > dst.len) return error.Corruption;

    if (strict) {
        try decodeSingleStream(dst[0..op2], src[6..s1End], decoder);
        try decodeSingleStream(dst[op2..op3], src[s1End..s2End], decoder);
        try decodeSingleStream(dst[op3..op4], src[s2End..s3End], decoder);
        try decodeSingleStream(dst[op4..], src[s4Start..], decoder);
    } else {
        try decodeSingleStreamLenient(dst[0..op2], src[6..s1End], decoder);
        try decodeSingleStreamLenient(dst[op2..op3], src[s1End..s2End], decoder);
        try decodeSingleStreamLenient(dst[op3..op4], src[s2End..s3End], decoder);
        try decodeSingleStreamLenient(dst[op4..], src[s4Start..], decoder);
    }
}

/// Convenience entry point: parse a complete literals payload (tree description
/// plus bitstreams) into `dst`. Uses one stream when `dst.len < 256` and four
/// otherwise, the encoder's rule; the frame decoder reads the count from the
/// literals section header instead.
pub fn decompressHuffmanBlock(allocator: std.mem.Allocator, dst: []u8, src: []const u8) errors.ZstdError!usize {
    if (src.len < 1) return error.SrcSizeWrong;
    var huffWeight: [256]u8 = @splat(0);
    var rankStats: [max_table_log + 1]u32 = @splat(0);
    var nbSymbols: usize = 0;
    var tableLog: u8 = 0;

    const header_read = try readStats(&huffWeight, &rankStats, &nbSymbols, &tableLog, src, allocator);
    var decoder = try buildDecoder(allocator, huffWeight[0..nbSymbols], tableLog);
    defer decoder.deinit();

    const bitstream_data = src[header_read..];
    // Lenient: this entry point serves encoder tests and utilities, where the
    // native encoder may emit extra padding. Frame decoding uses the strict
    // single/4-stream entry points above.
    if (dst.len < 256) {
        try decodeSingleStreamLenient(dst, bitstream_data, &decoder);
    } else {
        try decode4StreamsLenient(dst, bitstream_data, &decoder);
    }
    return dst.len;
}

// Tests

const testing = std.testing;

test "buildDecoder simple" {
    // weights {2,1,1}: total = 2+1+1 = 4 -> tableLog 2, 4 cells.
    const weights = [_]u8{ 2, 1, 1 };
    var dec = try buildDecoder(testing.allocator, &weights, 2);
    defer dec.deinit();
    try testing.expectEqual(@as(u8, 2), dec.max_bits);
    try testing.expectEqual(@as(usize, 4), dec.table.len);
}

test "buildDecoder single weight" {
    const weights = [_]u8{ 2, 2 };
    var dec = try buildDecoder(testing.allocator, &weights, 2);
    defer dec.deinit();
    try testing.expectEqual(@as(u8, 2), dec.max_bits);
}

test "buildDecoder empty" {
    const weights = [_]u8{};
    try testing.expectError(error.InvalidHuffmanTable, buildDecoder(testing.allocator, &weights, 2));
}

test "buildDecoder all zero" {
    const weights = [_]u8{ 0, 0, 0 };
    try testing.expectError(error.InvalidHuffmanTable, buildDecoder(testing.allocator, &weights, 2));
}

test "buildDecoder weight too large" {
    const weights = [_]u8{ 3, 1 };
    try testing.expectError(error.InvalidHuffmanTable, buildDecoder(testing.allocator, &weights, 2));
}

test "buildDecoder rejects zero table log" {
    const weights = [_]u8{1};
    try testing.expectError(error.InvalidHuffmanTable, buildDecoder(testing.allocator, &weights, 0));
}

test "buildDecoder rejects table log above the format maximum" {
    const weights = [_]u8{ 13, 1 };
    try testing.expectError(error.InvalidHuffmanTable, buildDecoder(testing.allocator, &weights, 13));
}

test "buildDecoder accepts the format maximum table log" {
    // A depth-12 code is legal even though encoders rarely produce one.
    const weights = [_]u8{ 12, 12 };
    var dec = try buildDecoder(testing.allocator, &weights, 12);
    defer dec.deinit();
    try testing.expectEqual(@as(u8, 12), dec.max_bits);
    try testing.expectEqual(@as(usize, 4096), dec.table.len);
}

test "buildDecoder fills every cell exactly once" {
    // A complete code: weights {1,1,2,2,2} sum(2^(w-1)) = 1+1+2+2+2 = 8.
    // Larger weights mean shorter codes: weight 2 -> 2-bit codes, and the
    // weight-1 symbols get the longest (3-bit) codes.
    const weights = [_]u8{ 1, 1, 2, 2, 2 };
    var dec = try buildDecoder(testing.allocator, &weights, 3);
    defer dec.deinit();
    try testing.expectEqual(@as(usize, 8), dec.table.len);
    var seen_long = false;
    var seen_short = false;
    for (dec.table) |e| {
        try testing.expect(e.symbol < weights.len);
        // No cell may be left at the zero-initialised sentinel.
        try testing.expect(e.nbBits >= 1);
        if (e.nbBits == 3) seen_long = true;
        if (e.nbBits == 2) seen_short = true;
    }
    try testing.expect(seen_long);
    try testing.expect(seen_short);
}

test "buildDecoder symbols populated" {
    const weights = [_]u8{ 2, 1, 1 };
    var dec = try buildDecoder(testing.allocator, &weights, 2);
    defer dec.deinit();
    var found = [_]bool{ false, false, false };
    for (dec.table) |e| {
        if (e.symbol < 3) found[e.symbol] = true;
    }
    try testing.expect(found[0]);
    try testing.expect(found[1]);
    try testing.expect(found[2]);
}

test "decompressHuffmanBlock empty" {
    var dst: [4]u8 = undefined;
    try testing.expectError(
        error.SrcSizeWrong,
        decompressHuffmanBlock(testing.allocator, &dst, &[_]u8{}),
    );
}

test "decodeSingleStreamLenient tolerates padding" {
    // Lenient mode exists for encoder tests; it must still decode correctly
    // on well-formed input. Weights {2,1,1} tableLog 2 give a 4-cell table;
    // an all-zero stream decodes to symbol 0 repeatedly.
    const weights = [_]u8{ 2, 1, 1 };
    var dec = try buildDecoder(testing.allocator, &weights, 2);
    defer dec.deinit();
    var src = [_]u8{ 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01 };
    var dst: [4]u8 = undefined;
    try decodeSingleStreamLenient(&dst, &src, &dec);
    for (dst) |b| try testing.expect(b < weights.len);
}

test "decodeSingleStream zero length is a no-op" {
    const weights = [_]u8{ 2, 1, 1 };
    var dec = try buildDecoder(testing.allocator, &weights, 2);
    defer dec.deinit();
    try decodeSingleStream(&[_]u8{}, &[_]u8{1}, &dec);
}

test "decode4Streams rejects a short jump table" {
    const weights = [_]u8{ 2, 1, 1 };
    var dec = try buildDecoder(testing.allocator, &weights, 2);
    defer dec.deinit();
    var dst: [16]u8 = undefined;
    try testing.expectError(
        error.Corruption,
        decode4Streams(&dst, &[_]u8{ 1, 0, 1, 0, 1, 0, 0, 0, 0 }, &dec),
    );
}

test "readStats direct representation" {
    // header 128 => 1 weight; nibble 1 means weight 1. weightTotal = 1,
    // tableLog = 1, rest = 2 - 1 = 1 -> implied last weight 1, so the code is
    // {1,1}: the two-symbol table a Huffman encoder emits for equal counts.
    var weights: [256]u8 = @splat(0);
    var ranks: [max_table_log + 1]u32 = @splat(0);
    var nbSymbols: usize = 0;
    var tableLog: u8 = 0;
    const src = [_]u8{ 128, 0x10 };
    const used = try readStats(&weights, &ranks, &nbSymbols, &tableLog, &src, testing.allocator);
    try testing.expectEqual(@as(usize, 2), used);
    try testing.expectEqual(@as(usize, 2), nbSymbols);
    try testing.expectEqual(@as(u8, 1), tableLog);
    try testing.expectEqual(@as(u8, 1), weights[0]);
    try testing.expectEqual(@as(u8, 1), weights[1]);
    try testing.expectEqual(@as(u32, 2), ranks[1]);
}

test "readStats rejects a direct table no Huffman tree could produce" {
    // header 128 => 1 weight; nibble 2 gives weight 2. Implied last weight is
    // also 2, so every code is one bit while the table log claims two. The
    // deep rank is empty, which no Huffman construction yields.
    var weights: [256]u8 = @splat(0);
    var ranks: [max_table_log + 1]u32 = @splat(0);
    var nbSymbols: usize = 0;
    var tableLog: u8 = 0;
    try testing.expectError(
        error.Corruption,
        readStats(&weights, &ranks, &nbSymbols, &tableLog, &[_]u8{ 128, 0x20 }, testing.allocator),
    );
}

test "readStats rejects a truncated direct header" {
    var weights: [256]u8 = @splat(0);
    var ranks: [max_table_log + 1]u32 = @splat(0);
    var nbSymbols: usize = 0;
    var tableLog: u8 = 0;
    try testing.expectError(
        error.SrcSizeWrong,
        readStats(&weights, &ranks, &nbSymbols, &tableLog, &[_]u8{ 200, 0x00 }, testing.allocator),
    );
}

test "readStats rejects a zero header" {
    var weights: [256]u8 = @splat(0);
    var ranks: [max_table_log + 1]u32 = @splat(0);
    var nbSymbols: usize = 0;
    var tableLog: u8 = 0;
    try testing.expectError(
        error.Corruption,
        readStats(&weights, &ranks, &nbSymbols, &tableLog, &[_]u8{0}, testing.allocator),
    );
}

test "readStats rejects an empty source" {
    var weights: [256]u8 = @splat(0);
    var ranks: [max_table_log + 1]u32 = @splat(0);
    var nbSymbols: usize = 0;
    var tableLog: u8 = 0;
    try testing.expectError(
        error.SrcSizeWrong,
        readStats(&weights, &ranks, &nbSymbols, &tableLog, &[_]u8{}, testing.allocator),
    );
}

test "readStats rejects an impossible weight" {
    // header 130 => 3 weights, nibbles 13, 40, 00 -> weights 1, 3, 4, 0.
    // weightTotal = 1 + 4 + 8 = 13, not a power of two pattern that yields a
    // valid tree, so this must be rejected.
    var weights: [256]u8 = @splat(0);
    var ranks: [max_table_log + 1]u32 = @splat(0);
    var nbSymbols: usize = 0;
    var tableLog: u8 = 0;
    try testing.expectError(
        error.Corruption,
        readStats(&weights, &ranks, &nbSymbols, &tableLog, &[_]u8{ 130, 0x13, 0x40 }, testing.allocator),
    );
}
