pub const ZstdError = error{
    Corruption,
    ChecksumWrong,
    DictionaryCorrupted,
    DictionaryWrong,
    ParameterOutOfBound,
    TableLogTooLarge,
    MaxSymbolValueTooLarge,
    MaxSymbolValueTooSmall,
    StageWrong,
    InitMissing,
    MemoryAllocation,
    WorkspaceTooSmall,
    DstSizeTooSmall,
    SrcSizeWrong,
    DstBufferNull,
    NoForwardProgressDestFull,
    NoForwardProgressInputEmpty,
    FrameIndexTooLarge,
    PrefixUnknown,
    VersionUnsupported,
    FrameParameterUnsupported,
    WindowTooLarge,
    UnsupportedFeature,
    InvalidMagic,
    InvalidFrameHeader,
    InvalidBlock,
    InvalidBlockSize,
    InvalidDictionary,
    InvalidFseTable,
    InvalidHuffmanTable,
    InvalidSequence,
    InvalidOffset,
    ContentSizeMismatch,
    AllocationFailure,
    GenericError,
    OutOfMemory,
};

pub fn errorToString(err: ZstdError) []const u8 {
    return switch (err) {
        error.Corruption => "corruption_detected",
        error.ChecksumWrong => "checksum_wrong",
        error.DictionaryCorrupted => "dictionary_corrupted",
        error.DictionaryWrong => "dictionary_wrong",
        error.ParameterOutOfBound => "parameter_outOfBound",
        error.TableLogTooLarge => "tableLog_tooLarge",
        error.MaxSymbolValueTooLarge => "maxSymbolValue_tooLarge",
        error.MaxSymbolValueTooSmall => "maxSymbolValue_tooSmall",
        error.StageWrong => "stage_wrong",
        error.InitMissing => "init_missing",
        error.MemoryAllocation => "memory_allocation",
        error.WorkspaceTooSmall => "workSpace_tooSmall",
        error.DstSizeTooSmall => "dstSize_tooSmall",
        error.SrcSizeWrong => "srcSize_wrong",
        error.DstBufferNull => "dstBuffer_null",
        error.NoForwardProgressDestFull => "noForwardProgress_destFull",
        error.NoForwardProgressInputEmpty => "noForwardProgress_inputEmpty",
        error.FrameIndexTooLarge => "frameIndex_tooLarge",
        error.PrefixUnknown => "prefix_unknown",
        error.VersionUnsupported => "version_unsupported",
        error.FrameParameterUnsupported => "frameParameter_unsupported",
        error.WindowTooLarge => "windowTooLarge",
        error.UnsupportedFeature => "unsupported_feature",
        error.InvalidMagic => "invalid_magic",
        error.InvalidFrameHeader => "invalid_frame_header",
        error.InvalidBlock => "invalid_block",
        error.InvalidBlockSize => "invalid_block_size",
        error.InvalidDictionary => "invalid_dictionary",
        error.InvalidFseTable => "invalid_fse_table",
        error.InvalidHuffmanTable => "invalid_huffman_table",
        error.InvalidSequence => "invalid_sequence",
        error.InvalidOffset => "invalid_offset",
        error.ContentSizeMismatch => "content_size_mismatch",
        error.AllocationFailure => "allocation_failure",
        error.GenericError => "generic_error",
        error.OutOfMemory => "out_of_memory",
    };
}
